### PR TITLE
unlock pg now that Rails 5 removed restriction

### PR DESCRIPTION
**Pull request by jmartin-r7**
`pg` had been locked due to Rails 4 requirements.  Now that https://github.com/rapid7/metasploit-framework/pull/13831 has landed, the restriction can be removed.

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by zeroSteiner** [comment]
I installed the build artifact on a fresh Ubuntu 20.04 system. It installed and started up without any issues and I did a quick check to ensure it included the expected changes which it did so I'm going to merge these in and trigger a new build.

**Pull request merged**
