### PR TITLE
update to postgres 9.6.20

### PR DESCRIPTION
**Pull request by jmartin-r7**
Update builds to utilize latest postges 9.6.x release.

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by adfoster-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by adfoster-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by adfoster-r7** [comment]
#### Ubuntu

Working as expected

```
msf6 auxiliary(scanner/mysql/mysql_login) > db_nmap 127.0.0.1
[*] Nmap: Starting Nmap 7.91 ( https://nmap.org ) at 2021-02-16 16:09 GMT
[*] Nmap: Nmap scan report for localhost (127.0.0.1)
[*] Nmap: Host is up (0.00023s latency).
[*] Nmap: Not shown: 967 closed ports, 30 filtered ports
[*] Nmap: PORT      STATE SERVICE
[*] Nmap: 53/tcp    open  domain
[*] Nmap: 5432/tcp  open  postgresql
[*] Nmap: 49163/tcp open  unknown
[*] Nmap: Nmap done: 1 IP address (1 host up) scanned in 5.99 seconds
msf6 auxiliary(scanner/mysql/mysql_login) > db_hosts
[-] The db_hosts command is DEPRECATED
[-] Use hosts instead
Hosts
=====
address    mac  name       os_name  os_flavor  os_sp  purpose  info  comments
-------    ---  ----       -------  ---------  -----  -------  ----  --------
127.0.0.1       localhost  Unknown                    device         
>> Mdm::Host.connection.exec_query("select version()")
=> 
#<ActiveRecord::Result:0x00007f52082b8e30
 @column_types=
  {"version"=>#<ActiveRecord::Type::Text:0x00007f520f339d08 @limit=nil, @precision=nil, @scale=nil>},
 @columns=["version"],
 @hash_rows=nil,
 @rows=[["PostgreSQL 9.6.20 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit"]]>
```

#### OSX

Working as expected:

```
msf6 auxiliary(scanner/mysql/mysql_login) > db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
>> Mdm::Host.connection.exec_query("select version()")
=> 
#<ActiveRecord::Result:0x000000010e5d5868
 @column_types={"version"=>#<ActiveRecord::Type::Text:0x000000011086b990 @limit=nil, @precision=nil, @scale=nil>},
 @columns=["version"],
 @hash_rows=nil,
 @rows=[["PostgreSQL 9.6.20 on x86_64-apple-darwin15.6.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit"]]>
```

#### Windows

I had no luck verifying that the `msfdb init` script on windows works. I ran into issues with spaces in usernames breaking the msfdb commands, and after creating a new account the script wasn't able to boot up thin:
image

That aside, as the scope of this ticket was updating the postgres version which works well in isolation:

```
c:\metasploit-framework>.\embedded\bin\psql -p 5433 --username=msf --password
psql (9.6.20)
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.
msf=> select version();
                           version
--------------------------------------------------------------
 PostgreSQL 9.6.20, compiled by Visual C++ build 1800, 64-bit
(1 row)
```

**Review by adfoster-r7 — APPROVED** [review]

**Pull request merged**
