### PR TITLE
Upgrading jemalloc & openssl for Apple Silicon support

### PR DESCRIPTION
**Pull request by Ishaanahuja7**
Packaging support for Apple Silicon.

Relevant [Issue](https://github.com/rapid7/metasploit-framework/issues/17628) in metasploit-framework and [PR](https://github.com/rapid7/metasploit-omnibus-cache/pull/4) in metasploit-omnibus-cache

### CODE REVIEW

**Comment by sempervictus** [comment]
@maintainers: please check out the linked MSF issue as @Ishaanahuja7 has the full output of a `bundle install` run from Framework's master. That output clearly shows the usual suspects like Nokogiri building natively on the ARM64 chip. I dont have metal on which to test, but purely external review indicates this is viable stuff.

Ping @jmartin-r7 & @smcintyre-r7 for eyes-on and to request dispatch to the actual maintainers of the omnibus repos.

**Comment by jmartin-r7** [comment]
@Ishaanahuja7 thank you for starting this process.

This PR will take a bit of time to get landed as we need to test all the dependency builds in an arm64 native macOS environment as well as figure out how we want to name and differentiate the native packages.

Support on for a `pkg` build on M1 hardware is definitely desired as we have confirmed a full native development environment is viable. A universal `pkg` is likely not in the cards for this project.

**Comment by jmartin-r7** [comment]
Thanks for your pull request! We require for all contributed code to come from a **from a unique branch** in your repository before it can be merged.

Please create a new branch in your fork of metasploit-omnibus and resubmit this from that branch.
If you are using Git on the command line that may look like:
```
# Checkout the master branch
git checkout master
# Create a new branch for your feature
git checkout -b <BRANCH_NAME>
# Add your new files
git add modules/my-cool-new-module
# Commit your changes with a relevant message
git commit
# Push your changes to GitHub
git push origin <BRANCH_NAME>
# Now browse to the following URL and create your pull request!
# - https://github.com/rapid7/metasploit-omnibus/pulls
```
This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

**Comment by Ishaanahuja7** [comment]
Continued [above](https://github.com/rapid7/metasploit-omnibus/pull/182)

**Pull request closed without merging**
