### PR TITLE
Update msfdb.erb

### PR DESCRIPTION
**Pull request by data0nf**
fix the error with new version of postgresql which does not support "local"

### CODE REVIEW

**Comment by busterb** [comment]
wow, new versions of postgresql remove support for domain sockets? Or is it just not supported across all OSes and this fixes a Windows issue?

https://www.postgresql.org/docs/10/static/auth-pg-hba-conf.html

**Comment by data0nf** [comment]
My bad, that only occurs on windows versions. Any workaround except this?

**Comment by busterb** [comment]
Try adding a check for `if Gem.win_platform?` to conditionally generate the right file per-Windows and non-Windows.

**Comment by busterb** [comment]
I tweaked your PR here: ed34c34
Thanks!

**Comment by data0nf** [comment]
No worries!

**Pull request merged**
